export const colors = {
  Primary_Color: '#DB3022',
  Backgournd_Color: '#F9F9F9',
  Text_Color: '#222222',
  Secondary_Text_Color: '#9B9B9B',
  White_Color: '#FFFFFF',
  Success_Color: '#2AA952',
  Error_Color: '#F01F0E',
  Star_Color: '#FFBA49',
  Gray_Color: '#9B9B9B',
  Transperen_Color: 'transparent',
  Black_Color_RGBA: 'rgba(0,0,0,0.4)',
  Text_Rating_Color: '#4F4F4F',
  Gray_Light_Color: '#F6F6F6',
  Gray_Dark_Color: '#BEA9A9',
  Yellow_Light_Color: '#E2BB8D',
  Blue_Dark_Color: '#151867',
  Action_Dialog_Blue: '#1C98F3',
  Yellow_Color: '#FFD700',
  Order_Status_Bar: '#00C6AE',
  Line_Status_Order: '#E0E0E0',
  Dot_Status_Order: '#C4C4C4'
};
